sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t loay317/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true loay317/docker-react npm run test
